In [125]:
import numpy as np

In [137]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [138]:
a.shape

(3, 2)

In [141]:
np.arange(1,15,3)

array([ 1,  4,  7, 10, 13])

In [143]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [147]:
np.full((3,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [150]:
a = np.array([1,2,3])
a.reshape(-1,1)

array([[1],
       [2],
       [3]])

In [151]:
a = np.array([[1,2],[3,4]])
a.flatten()

array([1, 2, 3, 4])

In [154]:
a = np.array([1,2,3,4,5])
a[[0,2]]

array([1, 3])

In [160]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
a[1:3,[1,3]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 6,  8],
       [10, 12]])

In [162]:
a = np.array([1,2])
a*2

array([2, 4])

In [163]:
def f(x):
    return x**2+1

a = np.array([1,2])
f(a)

array([2, 5])

In [166]:
b = np.array([2,3])
a*b

array([2, 6])

In [170]:
a = np.array([1,2,3,4])
np.max(a)

4

In [174]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
np.mean(a, axis=1)

[[1 2 3]
 [4 5 6]]


array([2., 5.])

In [197]:
a = np.array([1,2])
np.random.choice(a,p=[0.8,0.1])

ValueError: probabilities do not sum to 1

In [198]:
a = np.array([1,2])
b = np.array([3,4])
np.dot(a,b)

11

In [199]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)
np.dot(a,b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [201]:
a = np.array([1,2])
b = np.array([[1,2],[3,4]])
print(a)
print(b)
np.dot(b,a)

[1 2]
[[1 2]
 [3 4]]


array([ 5, 11])

In [208]:
a = np.array([3,4])
np.linalg.norm(a)

5.0

In [211]:
a = np.array([[1,2],[3,4]])
np.linalg.norm(a, axis=1)

array([2.23606798, 5.        ])

In [212]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
a.T

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [215]:
a = np.array([[1,2]])
a.T

array([[1],
       [2]])

In [214]:
a.reshape(-1,1)

array([[1],
       [2]])

In [219]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [220]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [221]:
a > 7

array([[False, False, False],
       [False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [224]:
a[:,np.array([True,False,True])]

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [230]:
a[a[:,0] >= 7,:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [229]:
a[:,0] >= 7

array([False, False,  True,  True])